/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// For each account type, optional meta information MAY be provided with these tags depending upon account type returned.  Intended choice - Due to cross language serialization issues the choice construct has been removed. It is the responsibility of the implementer to add programmatic logic for this complex type to detect, handle and or error when population of more than one element is present. 
    /// </summary>
    [DataContract]
    public partial class AccountMeta 
    {
        /// <summary>
        /// Gets or Sets LoanMeta
        /// </summary>
        [DataMember(Name="loanMeta", EmitDefaultValue=false)]
        public AccountMetaLoanMeta LoanMeta { get; set; }

        /// <summary>
        /// Gets or Sets CheckingSavingsMeta
        /// </summary>
        [DataMember(Name="checkingSavingsMeta", EmitDefaultValue=false)]
        public AccountMetaCheckingSavingsMeta CheckingSavingsMeta { get; set; }

        /// <summary>
        /// Gets or Sets CreditCardMeta
        /// </summary>
        [DataMember(Name="creditCardMeta", EmitDefaultValue=false)]
        public AccountMetaCreditCardMeta CreditCardMeta { get; set; }

        /// <summary>
        /// Gets or Sets InvestmentMeta
        /// </summary>
        [DataMember(Name="investmentMeta", EmitDefaultValue=false)]
        public AccountMetaInvestmentMeta InvestmentMeta { get; set; }

        /// <summary>
        /// Gets or Sets LineOfCreditMeta
        /// </summary>
        [DataMember(Name="lineOfCreditMeta", EmitDefaultValue=false)]
        public AccountMetaLineOfCreditMeta LineOfCreditMeta { get; set; }

        /// <summary>
        /// Gets or Sets MortgageMeta
        /// </summary>
        [DataMember(Name="mortgageMeta", EmitDefaultValue=false)]
        public AccountMetaMortgageMeta MortgageMeta { get; set; }

    }
}
