/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// The list of filter options for services requesting app data.  The options can be used in combination or by themselves.  It is up to the data source to either return the data requested or return a standard error identifying why the request was rejected. 
    /// </summary>
    [DataContract]
    public partial class AppFilter 
    {
        /// <summary>
        /// Gets or Sets AppIdList
        /// </summary>
        [DataMember(Name="appIdList", EmitDefaultValue=false)]
        public AppFilterAppIdList AppIdList { get; set; }

        /// <summary>
        /// Gets or Sets AppTypeList
        /// </summary>
        [DataMember(Name="appTypeList", EmitDefaultValue=false)]
        public AppFilterAppTypeList AppTypeList { get; set; }

        /// <summary>
        /// Gets or Sets VendorIdList
        /// </summary>
        [DataMember(Name="vendorIdList", EmitDefaultValue=false)]
        public AppFilterVendorIdList VendorIdList { get; set; }

        /// <summary>
        /// Gets or Sets AppHashList
        /// </summary>
        [DataMember(Name="appHashList", EmitDefaultValue=false)]
        public AppFilterAppHashList AppHashList { get; set; }

        /// <summary>
        /// Add this flag if you wish to query on apps that have or have NOT had their hash values validated.  Otherwise, leave this filter out. 
        /// </summary>
        /// <value>Add this flag if you wish to query on apps that have or have NOT had their hash values validated.  Otherwise, leave this filter out. </value>
        [DataMember(Name="isAppHashValidated", EmitDefaultValue=true)]
        public bool IsAppHashValidated { get; set; }

        /// <summary>
        /// Gets or Sets AppParameterIdList
        /// </summary>
        [DataMember(Name="appParameterIdList", EmitDefaultValue=false)]
        public AppFilterAppParameterIdList AppParameterIdList { get; set; }

        /// <summary>
        /// Gets or Sets ParameterNameList
        /// </summary>
        [DataMember(Name="parameterNameList", EmitDefaultValue=false)]
        public AppFilterParameterNameList ParameterNameList { get; set; }

        /// <summary>
        /// Gets or Sets ParameterScopeList
        /// </summary>
        [DataMember(Name="parameterScopeList", EmitDefaultValue=false)]
        public AppFilterParameterScopeList ParameterScopeList { get; set; }

        /// <summary>
        /// Gets or Sets ParameterTypeList
        /// </summary>
        [DataMember(Name="parameterTypeList", EmitDefaultValue=false)]
        public AppFilterParameterTypeList ParameterTypeList { get; set; }

        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public AccessProfileCustomData CustomData { get; set; }

    }
}
