/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
        /// <summary>
        /// Enumeration of the different types of cards. 
        /// </summary>
        /// <value>Enumeration of the different types of cards. </value>
        [TypeConverter(typeof(CustomEnumConverter<CardType>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CardType
        {
            
            /// <summary>
            /// Enum AtmEnum for Atm
            /// </summary>
            [EnumMember(Value = "Atm")]
            AtmEnum = 1,
            
            /// <summary>
            /// Enum CreditEnum for Credit
            /// </summary>
            [EnumMember(Value = "Credit")]
            CreditEnum = 2,
            
            /// <summary>
            /// Enum DebitEnum for Debit
            /// </summary>
            [EnumMember(Value = "Debit")]
            DebitEnum = 3,
            
            /// <summary>
            /// Enum HomeEquityEnum for HomeEquity
            /// </summary>
            [EnumMember(Value = "HomeEquity")]
            HomeEquityEnum = 4,
            
            /// <summary>
            /// Enum PrepaidEnum for Prepaid
            /// </summary>
            [EnumMember(Value = "Prepaid")]
            PrepaidEnum = 5
        }
}
