/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// Intended choice - Due to cross language serialization issues the choice construct has been removed. It is the responsibility of the implementer to add programmatic logic for this complex type to detect, handle and or error when population of more than one element is present. Details related to specific collateral for a loan. 
    /// </summary>
    [DataContract]
    public partial class Collateral 
    {
        /// <summary>
        /// Gets or Sets MotorVehicleCollateral
        /// </summary>
        [DataMember(Name="motorVehicleCollateral", EmitDefaultValue=false)]
        public CollateralMotorVehicleCollateral MotorVehicleCollateral { get; set; }

        /// <summary>
        /// Gets or Sets AircraftCollateral
        /// </summary>
        [DataMember(Name="aircraftCollateral", EmitDefaultValue=false)]
        public CollateralAircraftCollateral AircraftCollateral { get; set; }

        /// <summary>
        /// Gets or Sets ShipCollateral
        /// </summary>
        [DataMember(Name="shipCollateral", EmitDefaultValue=false)]
        public CollateralShipCollateral ShipCollateral { get; set; }

        /// <summary>
        /// Gets or Sets TrailerCollateral
        /// </summary>
        [DataMember(Name="trailerCollateral", EmitDefaultValue=false)]
        public CollateralTrailerCollateral TrailerCollateral { get; set; }

        /// <summary>
        /// Gets or Sets BoatCollateral
        /// </summary>
        [DataMember(Name="boatCollateral", EmitDefaultValue=false)]
        public CollateralBoatCollateral BoatCollateral { get; set; }

        /// <summary>
        /// Gets or Sets OtherTitledCollateral
        /// </summary>
        [DataMember(Name="otherTitledCollateral", EmitDefaultValue=false)]
        public CollateralOtherTitledCollateral OtherTitledCollateral { get; set; }

        /// <summary>
        /// Gets or Sets MobileHomeCollateral
        /// </summary>
        [DataMember(Name="mobileHomeCollateral", EmitDefaultValue=false)]
        public CollateralMobileHomeCollateral MobileHomeCollateral { get; set; }

        /// <summary>
        /// Gets or Sets RealEstateCollateral
        /// </summary>
        [DataMember(Name="realEstateCollateral", EmitDefaultValue=false)]
        public CollateralRealEstateCollateral RealEstateCollateral { get; set; }

        /// <summary>
        /// Gets or Sets UccCollateral
        /// </summary>
        [DataMember(Name="uccCollateral", EmitDefaultValue=false)]
        public CollateralUccCollateral UccCollateral { get; set; }

        /// <summary>
        /// Gets or Sets SavingsCDCollateral
        /// </summary>
        [DataMember(Name="savingsCDCollateral", EmitDefaultValue=false)]
        public CollateralSavingsCDCollateral SavingsCDCollateral { get; set; }

        /// <summary>
        /// Gets or Sets SecuritiesCollateral
        /// </summary>
        [DataMember(Name="securitiesCollateral", EmitDefaultValue=false)]
        public CollateralSecuritiesCollateral SecuritiesCollateral { get; set; }

        /// <summary>
        /// Gets or Sets LetterOfCreditCollateral
        /// </summary>
        [DataMember(Name="letterOfCreditCollateral", EmitDefaultValue=false)]
        public CollateralLetterOfCreditCollateral LetterOfCreditCollateral { get; set; }

        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public AccessProfileCustomData CustomData { get; set; }

    }
}
