/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// Definition for the app in the configuration and its parameters. 
    /// </summary>
    [DataContract]
    public partial class ConfigurationFinancialInstitutionApp 
    {
        /// <summary>
        /// The unique identifier for the configuration, financial institution, app and parameter combination. 
        /// </summary>
        /// <value>The unique identifier for the configuration, financial institution, app and parameter combination. </value>
        [DataMember(Name="configurationFiAppId", EmitDefaultValue=false)]
        public string ConfigurationFiAppId { get; set; }

        /// <summary>
        /// The app id is the unique identifier that identifies the application. 
        /// </summary>
        /// <value>The app id is the unique identifier that identifies the application. </value>
        [DataMember(Name="appId", EmitDefaultValue=false)]
        public string AppId { get; set; }

        /// <summary>
        /// The description of the app if it has been customimized for this configuration financial institution. 
        /// </summary>
        /// <value>The description of the app if it has been customimized for this configuration financial institution. </value>
        [DataMember(Name="configurationFiAppDescription", EmitDefaultValue=false)]
        public string ConfigurationFiAppDescription { get; set; }

        /// <summary>
        /// Gets or Sets ConfigurationFiAppParameterList
        /// </summary>
        [DataMember(Name="configurationFiAppParameterList", EmitDefaultValue=false)]
        public ConfigurationFinancialInstitutionAppConfigurationFiAppParameterList ConfigurationFiAppParameterList { get; set; }

        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public AccessProfileCustomData CustomData { get; set; }

    }
}
