/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ContactContactPointInstantMessage 
    {
        /// <summary>
        /// Instant Messaging Service.  Examples would be Google IM, Jabber, AOL, Yahoo, Facebook, Skype, etc.  Not a restricted value as these services often change. 
        /// </summary>
        /// <value>Instant Messaging Service.  Examples would be Google IM, Jabber, AOL, Yahoo, Facebook, Skype, etc.  Not a restricted value as these services often change. </value>
        [DataMember(Name="messagingService", EmitDefaultValue=false)]
        public string MessagingService { get; set; }

        /// <summary>
        /// Contact user name within the instant messaging platform. 
        /// </summary>
        /// <value>Contact user name within the instant messaging platform. </value>
        [DataMember(Name="user", EmitDefaultValue=false)]
        public string User { get; set; }

    }
}
