/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// A credit limit increase request. 
    /// </summary>
    [DataContract]
    public partial class CreditLimitIncreaseRequest 
    {
        /// <summary>
        /// The date on which the credit limit increase request was made. 
        /// </summary>
        /// <value>The date on which the credit limit increase request was made. </value>
        [DataMember(Name="requestDate", EmitDefaultValue=false)]
        public string RequestDate { get; set; }

        /// <summary>
        /// The date on which the credit limit was increased. 
        /// </summary>
        /// <value>The date on which the credit limit was increased. </value>
        [DataMember(Name="limitIncreaseDate", EmitDefaultValue=false)]
        public string LimitIncreaseDate { get; set; }

        /// <summary>
        /// Amount of credit limit increase requested. 
        /// </summary>
        /// <value>Amount of credit limit increase requested. </value>
        [DataMember(Name="newLimitRequest", EmitDefaultValue=true)]
        public decimal NewLimitRequest { get; set; }

        /// <summary>
        /// A general memo field.  This field can be used to provide details on why an increase was requested. 
        /// </summary>
        /// <value>A general memo field.  This field can be used to provide details on why an increase was requested. </value>
        [DataMember(Name="memo", EmitDefaultValue=false)]
        public string Memo { get; set; }

    }
}
