/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// The list of filter options for services requesting credential group data.  The options can be used in combination or by themselves. It is up to the data source to either return or affect the data requested or return a standard error identifying why the request was rejected. 
    /// </summary>
    [DataContract]
    public partial class CredentialGroupFilter 
    {
        /// <summary>
        /// Gets or Sets FiUserIdList
        /// </summary>
        [DataMember(Name="fiUserIdList", EmitDefaultValue=false)]
        public CredentialGroupFilterFiUserIdList FiUserIdList { get; set; }

        /// <summary>
        /// Gets or Sets PartyIdList
        /// </summary>
        [DataMember(Name="partyIdList", EmitDefaultValue=false)]
        public AccountPartyIdList PartyIdList { get; set; }

        /// <summary>
        /// Gets or Sets UserIdList
        /// </summary>
        [DataMember(Name="userIdList", EmitDefaultValue=false)]
        public CredentialGroupFilterUserIdList UserIdList { get; set; }

        /// <summary>
        /// Gets or Sets UserIdTypeList
        /// </summary>
        [DataMember(Name="userIdTypeList", EmitDefaultValue=false)]
        public CredentialGroupFilterUserIdTypeList UserIdTypeList { get; set; }

        /// <summary>
        /// Gets or Sets RelationshipIdList
        /// </summary>
        [DataMember(Name="relationshipIdList", EmitDefaultValue=false)]
        public AccountFilterRelationshipIdList RelationshipIdList { get; set; }

        /// <summary>
        /// Gets or Sets AccountIdList
        /// </summary>
        [DataMember(Name="accountIdList", EmitDefaultValue=false)]
        public AccountFilterAccountIdList AccountIdList { get; set; }

        /// <summary>
        /// Gets or Sets AccountStatusList
        /// </summary>
        [DataMember(Name="accountStatusList", EmitDefaultValue=false)]
        public AccountFilterAccountStatusList AccountStatusList { get; set; }

        /// <summary>
        /// Gets or Sets CredentialTypeList
        /// </summary>
        [DataMember(Name="credentialTypeList", EmitDefaultValue=false)]
        public ActivityCredentialTypesRequiredList CredentialTypeList { get; set; }

        /// <summary>
        /// Gets or Sets DeliveryChannelList
        /// </summary>
        [DataMember(Name="deliveryChannelList", EmitDefaultValue=false)]
        public CredentialGroupDeliveryChannelList DeliveryChannelList { get; set; }

        /// <summary>
        /// Gets or Sets VerifyCredentialGroupList
        /// </summary>
        [DataMember(Name="verifyCredentialGroupList", EmitDefaultValue=false)]
        public ActivityCredentialsProvidedList VerifyCredentialGroupList { get; set; }

        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public AccessProfileCustomData CustomData { get; set; }

        /// <summary>
        /// Gets or Sets AccountIdentificationList
        /// </summary>
        [DataMember(Name="accountIdentificationList", EmitDefaultValue=false)]
        public AccountFilterAccountIdentificationList AccountIdentificationList { get; set; }

    }
}
