/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// Details related to delinquency notices. It describes/details the actions taken when the loan is in a delinquent state. 
    /// </summary>
    [DataContract]
    public partial class DelinquencyNotice 
    {
        /// <summary>
        /// Unique ID to identify the delinquency notice within the back end system. 
        /// </summary>
        /// <value>Unique ID to identify the delinquency notice within the back end system. </value>
        [DataMember(Name="delinquencyNoticeId", EmitDefaultValue=false)]
        public string DelinquencyNoticeId { get; set; }

        /// <summary>
        /// Code to identify the type of delinquency notice. FIs may have multiple delinquency notices; thats why they may need to identify by code. 
        /// </summary>
        /// <value>Code to identify the type of delinquency notice. FIs may have multiple delinquency notices; thats why they may need to identify by code. </value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// Number of days before a delinquency notice is generated. 
        /// </summary>
        /// <value>Number of days before a delinquency notice is generated. </value>
        [DataMember(Name="delinquencyNoticeDays", EmitDefaultValue=true)]
        public int DelinquencyNoticeDays { get; set; }

        /// <summary>
        /// Number of days delinquent before line of credit or credit card is locked. 
        /// </summary>
        /// <value>Number of days delinquent before line of credit or credit card is locked. </value>
        [DataMember(Name="delinquencyLockDays", EmitDefaultValue=true)]
        public int DelinquencyLockDays { get; set; }

        /// <summary>
        /// Description text for delinquency notices. 
        /// </summary>
        /// <value>Description text for delinquency notices. </value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

    }
}
