/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class FieldRequirement 
    {
        /// <summary>
        /// Identifier for the field requirement. 
        /// </summary>
        /// <value>Identifier for the field requirement. </value>
        [DataMember(Name="fieldRequirementId", EmitDefaultValue=false)]
        public string FieldRequirementId { get; set; }

        /// <summary>
        /// Technical requirement to be handled programatically as part of presentation / interaction. examples \&quot;A-Z\&quot;, \&quot;0-9\&quot;, \&quot;Alphanumeric\&quot; 
        /// </summary>
        /// <value>Technical requirement to be handled programatically as part of presentation / interaction. examples \&quot;A-Z\&quot;, \&quot;0-9\&quot;, \&quot;Alphanumeric\&quot; </value>
        [DataMember(Name="fieldTechnicalRequirement", EmitDefaultValue=false)]
        public string FieldTechnicalRequirement { get; set; }

        /// <summary>
        /// The value of a valid population for the response. 
        /// </summary>
        /// <value>The value of a valid population for the response. </value>
        [DataMember(Name="fieldSelection", EmitDefaultValue=false)]
        public string FieldSelection { get; set; }

        /// <summary>
        /// Description of the requirement. Available to optionally replace or modify fieldPrompt. 
        /// </summary>
        /// <value>Description of the requirement. Available to optionally replace or modify fieldPrompt. </value>
        [DataMember(Name="fieldRequirementDescription", EmitDefaultValue=false)]
        public string FieldRequirementDescription { get; set; }

        /// <summary>
        /// The format of the content of fieldRequirement. Example: Java Script, Pattern, HTML, C# snippet. 
        /// </summary>
        /// <value>The format of the content of fieldRequirement. Example: Java Script, Pattern, HTML, C# snippet. </value>
        [DataMember(Name="fieldRequirementType", EmitDefaultValue=false)]
        public string FieldRequirementType { get; set; }

        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public AccessProfileCustomData CustomData { get; set; }

    }
}
