/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// Field not supported by the end point.  Specify the XSD path and any comments as to why it isnt supported. 
    /// </summary>
    [DataContract]
    public partial class FieldNotSupported 
    {
        /// <summary>
        /// An XSD file name in the CUFX library that is the parent of the field that is not supported. For example: Party.xsd 
        /// </summary>
        /// <value>An XSD file name in the CUFX library that is the parent of the field that is not supported. For example: Party.xsd </value>
        [DataMember(Name="xsdFile", EmitDefaultValue=false)]
        public string XsdFile { get; set; }

        /// <summary>
        /// An XPath statement that identifies the XSD elements related of the field that is not supported. For example: /partyList/party/characteristics/individual/citizenshipList/_* 
        /// </summary>
        /// <value>An XPath statement that identifies the XSD elements related of the field that is not supported. For example: /partyList/party/characteristics/individual/citizenshipList/_* </value>
        [DataMember(Name="xsdXPath", EmitDefaultValue=false)]
        public string XsdXPath { get; set; }

        /// <summary>
        /// Comment as to why the field(s) is/are not supported. For example: This end point does not support citizenship as the back end core does not support this concept. 
        /// </summary>
        /// <value>Comment as to why the field(s) is/are not supported. For example: This end point does not support citizenship as the back end core does not support this concept. </value>
        [DataMember(Name="comment", EmitDefaultValue=false)]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public AccessProfileCustomData CustomData { get; set; }

    }
}
