/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// Describes individual line item amounts. 
    /// </summary>
    [DataContract]
    public partial class LineItem 
    {
        /// <summary>
        /// The line item identification number. If provided, each line item id should be unique. 
        /// </summary>
        /// <value>The line item identification number. If provided, each line item id should be unique. </value>
        [DataMember(Name="lineItemId", EmitDefaultValue=false)]
        public string LineItemId { get; set; }

        /// <summary>
        /// The line item reference. Provides for alternate cross reference. 
        /// </summary>
        /// <value>The line item reference. Provides for alternate cross reference. </value>
        [DataMember(Name="lineItemReference", EmitDefaultValue=false)]
        public string LineItemReference { get; set; }

        /// <summary>
        /// The description of the line item. 
        /// </summary>
        /// <value>The description of the line item. </value>
        [DataMember(Name="lineItemDescription", EmitDefaultValue=false)]
        public string LineItemDescription { get; set; }

        /// <summary>
        /// The date the line item was applied to the total amount. 
        /// </summary>
        /// <value>The date the line item was applied to the total amount. </value>
        [DataMember(Name="lineItemDate", EmitDefaultValue=false)]
        public DateTime LineItemDate { get; set; }

        /// <summary>
        /// Gets or Sets LineItemAmount
        /// </summary>
        [DataMember(Name="lineItemAmount", EmitDefaultValue=false)]
        public AccountAccountEscheatAmount LineItemAmount { get; set; }

    }
}
