/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
        /// <summary>
        /// The parameter is set for each individual user logged into a computer. For example: A Windows HKEY_CURRENT_USER registry entry or a Machine.config file. The parameter applies to the entire machine. For example: A Windows HKEY_LOCAL_MACHINE setting for security. The parameter applies to the specific application. For example: An IIS entry in the web.config file. For example: The parameter applies to all financial institutions within a configuration. To find the current value for the parameter within the configuration see configuration->configurationAppList->configurationApp-> configurationAppParameterList->configurationAppParameter->currentValue The parameter applies to a specific financial institution that owns the license. For example: An IIS entry in the web.config file. To find the current value for the parameter for the financial institution see configuration->configurationFiList->financialInstitution->configurationFiApp-> configurationFiAppParameterList->configurationFiAppParameter->currentValue The parameter applies to the current session only. For example: An session specific parameter. Some other parameter scope that has yet to be defined. Please request addition to specification if you believe others will benefit by the addition. 
        /// </summary>
        /// <value>The parameter is set for each individual user logged into a computer. For example: A Windows HKEY_CURRENT_USER registry entry or a Machine.config file. The parameter applies to the entire machine. For example: A Windows HKEY_LOCAL_MACHINE setting for security. The parameter applies to the specific application. For example: An IIS entry in the web.config file. For example: The parameter applies to all financial institutions within a configuration. To find the current value for the parameter within the configuration see configuration->configurationAppList->configurationApp-> configurationAppParameterList->configurationAppParameter->currentValue The parameter applies to a specific financial institution that owns the license. For example: An IIS entry in the web.config file. To find the current value for the parameter for the financial institution see configuration->configurationFiList->financialInstitution->configurationFiApp-> configurationFiAppParameterList->configurationFiAppParameter->currentValue The parameter applies to the current session only. For example: An session specific parameter. Some other parameter scope that has yet to be defined. Please request addition to specification if you believe others will benefit by the addition. </value>
        [TypeConverter(typeof(CustomEnumConverter<ParameterScope>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ParameterScope
        {
            
            /// <summary>
            /// Enum UserEnum for User
            /// </summary>
            [EnumMember(Value = "User")]
            UserEnum = 1,
            
            /// <summary>
            /// Enum MachineEnum for Machine
            /// </summary>
            [EnumMember(Value = "Machine")]
            MachineEnum = 2,
            
            /// <summary>
            /// Enum ApplicationEnum for Application
            /// </summary>
            [EnumMember(Value = "Application")]
            ApplicationEnum = 3,
            
            /// <summary>
            /// Enum ConfigurationEnum for Configuration
            /// </summary>
            [EnumMember(Value = "Configuration")]
            ConfigurationEnum = 4,
            
            /// <summary>
            /// Enum FinancialInstitutionEnum for FinancialInstitution
            /// </summary>
            [EnumMember(Value = "FinancialInstitution")]
            FinancialInstitutionEnum = 5,
            
            /// <summary>
            /// Enum SessionEnum for Session
            /// </summary>
            [EnumMember(Value = "Session")]
            SessionEnum = 6,
            
            /// <summary>
            /// Enum OtherEnum for Other
            /// </summary>
            [EnumMember(Value = "Other")]
            OtherEnum = 7
        }
}
