/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// Delete definition for PartyAssociationMessage
    /// </summary>
    [DataContract]
    public partial class PartyAssociationMessageDelete 
    {
        /// <summary>
        /// Gets or Sets MessageContext
        /// </summary>
        [DataMember(Name="messageContext", EmitDefaultValue=false)]
        public MessageContext MessageContext { get; set; }

        /// <summary>
        /// Gets or Sets PartyAssociationFilter
        /// </summary>
        [DataMember(Name="partyAssociationFilter", EmitDefaultValue=false)]
        public PartyAssociationFilter PartyAssociationFilter { get; set; }

        /// <summary>
        /// Gets or Sets PartyAssociationList
        /// </summary>
        [DataMember(Name="partyAssociationList", EmitDefaultValue=false)]
        public PartyAssociationList PartyAssociationList { get; set; }

    }
}
