/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// Individual (parent) is an officer or a manager of an organization (child). 
    /// </summary>
    [DataContract]
    public partial class PartyAssociationPartyAssociationTypeOfficerManager 
    {
        /// <summary>
        /// Pagination support. Current page of information presented in the message response. Typically used in combination with totalPages and pageSize. 
        /// </summary>
        /// <value>Pagination support. Current page of information presented in the message response. Typically used in combination with totalPages and pageSize. </value>
        [DataMember(Name="currentPage", EmitDefaultValue=true)]
        public int CurrentPage { get; set; }

        /// <summary>
        /// Pagination support. Total pages of information available as a result of the query. Typically used in combination with currentPage and pageSize. 
        /// </summary>
        /// <value>Pagination support. Total pages of information available as a result of the query. Typically used in combination with currentPage and pageSize. </value>
        [DataMember(Name="totalPages", EmitDefaultValue=true)]
        public int TotalPages { get; set; }

        /// <summary>
        /// Pagination support. The total number of records that may be returned as part of 1 page. Typically used in combination with currentPage and totalPages. 
        /// </summary>
        /// <value>Pagination support. The total number of records that may be returned as part of 1 page. Typically used in combination with currentPage and totalPages. </value>
        [DataMember(Name="pageSize", EmitDefaultValue=true)]
        public int PageSize { get; set; }

        /// <summary>
        /// Pagination support. The record position index of the current message response. 
        /// </summary>
        /// <value>Pagination support. The record position index of the current message response. </value>
        [DataMember(Name="positionIndex", EmitDefaultValue=false)]
        public string PositionIndex { get; set; }

        /// <summary>
        /// Pagination support. The requested page value to be returned in the message response. 
        /// </summary>
        /// <value>Pagination support. The requested page value to be returned in the message response. </value>
        [DataMember(Name="returnPage", EmitDefaultValue=true)]
        public int ReturnPage { get; set; }

        /// <summary>
        /// Pagination support. The requested record position to be returned in the message response. 
        /// </summary>
        /// <value>Pagination support. The requested record position to be returned in the message response. </value>
        [DataMember(Name="returnPositionIndex", EmitDefaultValue=false)]
        public string ReturnPositionIndex { get; set; }


        /// <summary>
        /// On Board of Directors of an organization.  Excludes CEO. C level manager of an organization.  Excludes CFO. CFO or Finance Director at an organization. President of an organization. Sold proprietor of an organization. Vice President of an organization.  Excludes CFO/Finance Director. Executive Director of an organization.  Excludes CFO/Finance Director. Director of an organization. Manager of an organization. Treasurer at an organization. Secretary at an organization. Manager level not listed in other categories at an organization. Not a manager at an organization. 
        /// </summary>
        /// <value>On Board of Directors of an organization.  Excludes CEO. C level manager of an organization.  Excludes CFO. CFO or Finance Director at an organization. President of an organization. Sold proprietor of an organization. Vice President of an organization.  Excludes CFO/Finance Director. Executive Director of an organization.  Excludes CFO/Finance Director. Director of an organization. Manager of an organization. Treasurer at an organization. Secretary at an organization. Manager level not listed in other categories at an organization. Not a manager at an organization. </value>
        [TypeConverter(typeof(CustomEnumConverter<QualifierEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum QualifierEnum
        {
            
            /// <summary>
            /// Enum BoardOfDirectorsEnum for BoardOfDirectors
            /// </summary>
            [EnumMember(Value = "BoardOfDirectors")]
            BoardOfDirectorsEnum = 1,
            
            /// <summary>
            /// Enum CxOEnum for CxO
            /// </summary>
            [EnumMember(Value = "CxO")]
            CxOEnum = 2,
            
            /// <summary>
            /// Enum FinancialOfficerEnum for FinancialOfficer
            /// </summary>
            [EnumMember(Value = "FinancialOfficer")]
            FinancialOfficerEnum = 3,
            
            /// <summary>
            /// Enum PresidentEnum for President
            /// </summary>
            [EnumMember(Value = "President")]
            PresidentEnum = 4,
            
            /// <summary>
            /// Enum SoleProprietorEnum for SoleProprietor
            /// </summary>
            [EnumMember(Value = "SoleProprietor")]
            SoleProprietorEnum = 5,
            
            /// <summary>
            /// Enum VicePresidentEnum for VicePresident
            /// </summary>
            [EnumMember(Value = "VicePresident")]
            VicePresidentEnum = 6,
            
            /// <summary>
            /// Enum ExecutiveDirectorEnum for ExecutiveDirector
            /// </summary>
            [EnumMember(Value = "ExecutiveDirector")]
            ExecutiveDirectorEnum = 7,
            
            /// <summary>
            /// Enum DirectorEnum for Director
            /// </summary>
            [EnumMember(Value = "Director")]
            DirectorEnum = 8,
            
            /// <summary>
            /// Enum ManagerEnum for Manager
            /// </summary>
            [EnumMember(Value = "Manager")]
            ManagerEnum = 9,
            
            /// <summary>
            /// Enum TreasurerEnum for Treasurer
            /// </summary>
            [EnumMember(Value = "Treasurer")]
            TreasurerEnum = 10,
            
            /// <summary>
            /// Enum SecretaryEnum for Secretary
            /// </summary>
            [EnumMember(Value = "Secretary")]
            SecretaryEnum = 11,
            
            /// <summary>
            /// Enum OtherManagerEnum for OtherManager
            /// </summary>
            [EnumMember(Value = "OtherManager")]
            OtherManagerEnum = 12,
            
            /// <summary>
            /// Enum NonManagerEnum for NonManager
            /// </summary>
            [EnumMember(Value = "NonManager")]
            NonManagerEnum = 13
        }

        /// <summary>
        /// On Board of Directors of an organization.  Excludes CEO. C level manager of an organization.  Excludes CFO. CFO or Finance Director at an organization. President of an organization. Sold proprietor of an organization. Vice President of an organization.  Excludes CFO/Finance Director. Executive Director of an organization.  Excludes CFO/Finance Director. Director of an organization. Manager of an organization. Treasurer at an organization. Secretary at an organization. Manager level not listed in other categories at an organization. Not a manager at an organization. 
        /// </summary>
        /// <value>On Board of Directors of an organization.  Excludes CEO. C level manager of an organization.  Excludes CFO. CFO or Finance Director at an organization. President of an organization. Sold proprietor of an organization. Vice President of an organization.  Excludes CFO/Finance Director. Executive Director of an organization.  Excludes CFO/Finance Director. Director of an organization. Manager of an organization. Treasurer at an organization. Secretary at an organization. Manager level not listed in other categories at an organization. Not a manager at an organization. </value>
        [DataMember(Name="qualifier", EmitDefaultValue=true)]
        public QualifierEnum Qualifier { get; set; }

    }
}
