/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// The list of filter options for services requesting party data.  The options can be used in combination or by themselves. It is up to the data source to either return or affect the data requested or return a standard error identifying why the request was rejected. 
    /// </summary>
    [DataContract]
    public partial class PartyFilter 
    {
        /// <summary>
        /// Gets or Sets PartyIdList
        /// </summary>
        [DataMember(Name="partyIdList", EmitDefaultValue=false)]
        public AccountPartyIdList PartyIdList { get; set; }

        /// <summary>
        /// Gets or Sets RelationshipIdList
        /// </summary>
        [DataMember(Name="relationshipIdList", EmitDefaultValue=false)]
        public AccountFilterRelationshipIdList RelationshipIdList { get; set; }

        /// <summary>
        /// Gets or Sets ContactIdList
        /// </summary>
        [DataMember(Name="contactIdList", EmitDefaultValue=false)]
        public ActivityActivityRelatedToContactIdList ContactIdList { get; set; }

        /// <summary>
        /// Gets or Sets AccountIdList
        /// </summary>
        [DataMember(Name="accountIdList", EmitDefaultValue=false)]
        public AccountFilterAccountIdList AccountIdList { get; set; }

        /// <summary>
        /// Gets or Sets AccountStatusList
        /// </summary>
        [DataMember(Name="accountStatusList", EmitDefaultValue=false)]
        public AccountFilterAccountStatusList AccountStatusList { get; set; }

        /// <summary>
        /// Gets or Sets AccountAccountTypeList
        /// </summary>
        [DataMember(Name="accountAccountTypeList", EmitDefaultValue=false)]
        public PartyFilterAccountAccountTypeList AccountAccountTypeList { get; set; }

        /// <summary>
        /// Gets or Sets TaxIdList
        /// </summary>
        [DataMember(Name="taxIdList", EmitDefaultValue=false)]
        public ContactFilterTaxIdList TaxIdList { get; set; }

        /// <summary>
        /// Gets or Sets PartyTypeList
        /// </summary>
        [DataMember(Name="partyTypeList", EmitDefaultValue=false)]
        public FeeScheduleFilterPartyTypeList PartyTypeList { get; set; }

        /// <summary>
        /// Gets or Sets PartyStatusList
        /// </summary>
        [DataMember(Name="partyStatusList", EmitDefaultValue=false)]
        public PartyFilterPartyStatusList PartyStatusList { get; set; }

        /// <summary>
        /// Gets or Sets PartySubStatusList
        /// </summary>
        [DataMember(Name="partySubStatusList", EmitDefaultValue=false)]
        public PartyFilterPartySubStatusList PartySubStatusList { get; set; }

        /// <summary>
        /// If this is not provided, it will not return notes. If it is provided and its true, it will return all active non-expired notes. 
        /// </summary>
        /// <value>If this is not provided, it will not return notes. If it is provided and its true, it will return all active non-expired notes. </value>
        [DataMember(Name="includeNotesFlag", EmitDefaultValue=true)]
        public bool IncludeNotesFlag { get; set; }

        /// <summary>
        /// Gets or Sets PersonNameList
        /// </summary>
        [DataMember(Name="personNameList", EmitDefaultValue=false)]
        public PartyFilterPersonNameList PersonNameList { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationNameList
        /// </summary>
        [DataMember(Name="organizationNameList", EmitDefaultValue=false)]
        public PartyFilterOrganizationNameList OrganizationNameList { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationTypeList
        /// </summary>
        [DataMember(Name="organizationTypeList", EmitDefaultValue=false)]
        public PartyFilterOrganizationTypeList OrganizationTypeList { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationSubTypeList
        /// </summary>
        [DataMember(Name="organizationSubTypeList", EmitDefaultValue=false)]
        public PartyFilterOrganizationSubTypeList OrganizationSubTypeList { get; set; }

        /// <summary>
        /// Gets or Sets ContactList
        /// </summary>
        [DataMember(Name="contactList", EmitDefaultValue=false)]
        public InvestmentPartyInvestmentContactList ContactList { get; set; }

        /// <summary>
        /// Gets or Sets PartyDateCreatedDateRange
        /// </summary>
        [DataMember(Name="partyDateCreatedDateRange", EmitDefaultValue=false)]
        public AccessProfileFilterCreateAccessDateRange PartyDateCreatedDateRange { get; set; }

        /// <summary>
        /// Gets or Sets PartyCreatedByList
        /// </summary>
        [DataMember(Name="partyCreatedByList", EmitDefaultValue=false)]
        public CredentialGroupFilterUserIdList PartyCreatedByList { get; set; }

        /// <summary>
        /// Gets or Sets PartyDateModifiedDateRange
        /// </summary>
        [DataMember(Name="partyDateModifiedDateRange", EmitDefaultValue=false)]
        public AccessProfileFilterCreateAccessDateRange PartyDateModifiedDateRange { get; set; }

        /// <summary>
        /// Gets or Sets PartyModifiedByList
        /// </summary>
        [DataMember(Name="partyModifiedByList", EmitDefaultValue=false)]
        public CredentialGroupFilterUserIdList PartyModifiedByList { get; set; }

        /// <summary>
        /// Gets or Sets PartyDateDeletedDateRange
        /// </summary>
        [DataMember(Name="partyDateDeletedDateRange", EmitDefaultValue=false)]
        public AccessProfileFilterCreateAccessDateRange PartyDateDeletedDateRange { get; set; }

        /// <summary>
        /// Gets or Sets CustomData
        /// </summary>
        [DataMember(Name="customData", EmitDefaultValue=false)]
        public AccessProfileCustomData CustomData { get; set; }

        /// <summary>
        /// Gets or Sets AccountIdentificationList
        /// </summary>
        [DataMember(Name="accountIdentificationList", EmitDefaultValue=false)]
        public AccountFilterAccountIdentificationList AccountIdentificationList { get; set; }

    }
}
