/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
        /// <summary>
        /// Gets or Sets RelationshipStatus
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<RelationshipStatus>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum RelationshipStatus
        {
            
            /// <summary>
            /// Enum ActiveEnum for Active
            /// </summary>
            [EnumMember(Value = "Active")]
            ActiveEnum = 1,
            
            /// <summary>
            /// Enum ClosedEnum for Closed
            /// </summary>
            [EnumMember(Value = "Closed")]
            ClosedEnum = 2,
            
            /// <summary>
            /// Enum DeceasedEnum for Deceased
            /// </summary>
            [EnumMember(Value = "Deceased")]
            DeceasedEnum = 3,
            
            /// <summary>
            /// Enum InactiveEnum for Inactive
            /// </summary>
            [EnumMember(Value = "Inactive")]
            InactiveEnum = 4,
            
            /// <summary>
            /// Enum ProspectEnum for Prospect
            /// </summary>
            [EnumMember(Value = "Prospect")]
            ProspectEnum = 5,
            
            /// <summary>
            /// Enum RestrictedEnum for Restricted
            /// </summary>
            [EnumMember(Value = "Restricted")]
            RestrictedEnum = 6
        }
}
