/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// The party relationship type is the textual representation of what the party record represents to this relationship, such as primary or joint ownership, beneficiary or some other type of relationship. This value may be visible to the user and must be human-readable.  If the party does not have full ownership or responsibility of all accounts within the relationship, then the party should be related to those accounts via a party list within the account object.  Specific loan level ownership will also be in the accounts via a party list within the account object. 
    /// </summary>
    [DataContract]
    public partial class RelationshipPartyPartyRelationshipType 
    {
        /// <summary>
        /// Gets or Sets Holder
        /// </summary>
        [DataMember(Name="holder", EmitDefaultValue=false)]
        public DepositPartyDepositPartyRelationshipTypeHolder Holder { get; set; }

        /// <summary>
        /// Gets or Sets Beneficiary
        /// </summary>
        [DataMember(Name="beneficiary", EmitDefaultValue=false)]
        public DepositPartyDepositPartyRelationshipTypeBeneficiary Beneficiary { get; set; }

        /// <summary>
        /// Gets or Sets Agent
        /// </summary>
        [DataMember(Name="agent", EmitDefaultValue=false)]
        public DepositPartyDepositPartyRelationshipTypeAgent Agent { get; set; }

        /// <summary>
        /// Gets or Sets Payee
        /// </summary>
        [DataMember(Name="payee", EmitDefaultValue=false)]
        public LoanPartyLoanPartyRelationshipTypePayee Payee { get; set; }

        /// <summary>
        /// Gets or Sets Guarantor
        /// </summary>
        [DataMember(Name="guarantor", EmitDefaultValue=false)]
        public DepositPartyDepositPartyRelationshipTypeGuarantor Guarantor { get; set; }

        /// <summary>
        /// Gets or Sets CollateralGrantor
        /// </summary>
        [DataMember(Name="collateralGrantor", EmitDefaultValue=false)]
        public LoanPartyLoanPartyRelationshipTypeCollateralGrantor CollateralGrantor { get; set; }

        /// <summary>
        /// Gets or Sets SafeDepositBoxUser
        /// </summary>
        [DataMember(Name="safeDepositBoxUser", EmitDefaultValue=false)]
        public DepositPartyDepositPartyRelationshipTypeSafeDepositBoxUser SafeDepositBoxUser { get; set; }

    }
}
