/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
        /// <summary>
        /// An enumeration of possible actions Create a new session for this remote deposit session, if the amounts are to be provided, this would be passed with this Action Submit one or more of the images associated to the request The remote deposit request is currently under review, and is not currently approved. 
        /// </summary>
        /// <value>An enumeration of possible actions Create a new session for this remote deposit session, if the amounts are to be provided, this would be passed with this Action Submit one or more of the images associated to the request The remote deposit request is currently under review, and is not currently approved. </value>
        [TypeConverter(typeof(CustomEnumConverter<RemoteDepositAction>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum RemoteDepositAction
        {
            
            /// <summary>
            /// Enum CreateSessionEnum for CreateSession
            /// </summary>
            [EnumMember(Value = "CreateSession")]
            CreateSessionEnum = 1,
            
            /// <summary>
            /// Enum SubmitImageEnum for SubmitImage
            /// </summary>
            [EnumMember(Value = "SubmitImage")]
            SubmitImageEnum = 2,
            
            /// <summary>
            /// Enum CommitEnum for Commit
            /// </summary>
            [EnumMember(Value = "Commit")]
            CommitEnum = 3
        }
}
