/*
 * Credit Union Financial eXchange
 *
 * Credit Union Industry Standard. The following API examples are producedz using scripting methods to create a swagger representation of the XML/XSDs. In the event of any noted deviations, the published XSDs on www.cufxstandards.com are the basis of intended content and behavior. Please see https://bonifii.com/cufx-terms-of-use for the terms of use applicable for CUFX.
 *
 * The version of the OpenAPI document: 4.5
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using VyStar.ApiStandards.CUFX.Converters;

namespace VyStar.ApiStandards.CUFX.Models
{ 
    /// <summary>
    /// Details related to transaction fees. 
    /// </summary>
    [DataContract]
    public partial class TransactionFee 
    {
        /// <summary>
        /// Unique ID to identify the transaction fee in the back end system. 
        /// </summary>
        /// <value>Unique ID to identify the transaction fee in the back end system. </value>
        [DataMember(Name="transactionFeeId", EmitDefaultValue=false)]
        public string TransactionFeeId { get; set; }

        /// <summary>
        /// The date/time posted is the date the transaction fee was posted to the account. If this date is unavailable, it is acceptable to use the date that the transaction took place.  The date/time should be ISO 8601 UTC format.  yyyy-mm-ddThh:mmZ (2011-03-28T12:00Z) and yyyy-mm-dd (2011-03-28) formats are supported.  The time is assumed to be 00:00Z if omitted. If omitted then the transaction fee was posted at the same time as the transaction. 
        /// </summary>
        /// <value>The date/time posted is the date the transaction fee was posted to the account. If this date is unavailable, it is acceptable to use the date that the transaction took place.  The date/time should be ISO 8601 UTC format.  yyyy-mm-ddThh:mmZ (2011-03-28T12:00Z) and yyyy-mm-dd (2011-03-28) formats are supported.  The time is assumed to be 00:00Z if omitted. If omitted then the transaction fee was posted at the same time as the transaction. </value>
        [DataMember(Name="transactionFeeDateTimePosted", EmitDefaultValue=false)]
        public string TransactionFeeDateTimePosted { get; set; }

        /// <summary>
        /// Gets or Sets TransactionfeeAmount
        /// </summary>
        [DataMember(Name="transactionfeeAmount", EmitDefaultValue=false)]
        public AccountAccountEscheatAmount TransactionfeeAmount { get; set; }

        /// <summary>
        /// FI-defined code that identifies the fee in the core system. 
        /// </summary>
        /// <value>FI-defined code that identifies the fee in the core system. </value>
        [DataMember(Name="transactionFeeCode", EmitDefaultValue=false)]
        public string TransactionFeeCode { get; set; }

        /// <summary>
        /// FI-defined description for the fee. 
        /// </summary>
        /// <value>FI-defined description for the fee. </value>
        [DataMember(Name="transactionFeeDescription", EmitDefaultValue=false)]
        public string TransactionFeeDescription { get; set; }

    }
}
